#!/bin/bash

./stop
aconnect -x

sleep 1
/usr/bin/sensei -f /udata/source/app/source_sensei_config.json &
sleep 1
/usr/bin/python3 main  &
#nohup /usr/bin/python3 main 1>/udata/source/app/source_start.log 2>/udata/source/app/source_start_error.log &
sleep 2
sushi -r -c /udata/source/app/source_sushi_config.json --log-level=debug &
sleep 3
echo "Running aconnect"
aconnect 16 128
